// Global using directives

global using Microsoft.Xaml.Behaviors;
global using Prism.Ioc;
global using Prism.Mvvm;
global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Data;
global using System.Diagnostics;
global using System.IO.Ports;
global using System.Linq;
global using System.Management;
global using System.Net.Http;
global using System.Text;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Threading;
global using Newtonsoft.Json;
global using Telegram.Bot;
global using Telegram.Bot.Exceptions;
global using Telegram.Bot.Polling;
global using Telegram.Bot.Types;
global using Telegram.Bot.Types.Enums;
global using ToolGsm.Models;
global using ToolGsm.Views;
global using JsonSerializer = System.Text.Json.JsonSerializer;